#!/bin/bash

# TurfSheet Design Validation Script
# Enforces visual fidelity checks before committing
# Run this before and after implementation work

set -e

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🔍 TURFSHEET DESIGN VALIDATION"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "⚠️  MANDATORY VISUAL INSPECTION REQUIRED"
echo ""
echo "This script will guide you through critical design validation."
echo "You MUST complete all steps before continuing."
echo ""

echo "STEP 1: Open Both Versions in Browser"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Mockup (Target Design):"
echo "  → file:///home/cpbjr/WhitePineTech/Projects/TurfSheet/SiteExamples/index.html"
echo ""
echo "  React App (Your Implementation):"
echo "  → http://localhost:5173/"
echo ""
echo "  Open BOTH in separate browser windows/tabs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "STEP 2: Color Verification Checklist"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Use DevTools (F12) → Inspector → Computed Styles → color/background-color"
echo ""
echo "CRITICAL - These colors MUST match EXACTLY:"
echo ""
echo "  1. Sidebar Background"
echo "     ✓ CORRECT:   #73A657 (Turf Green - visible green bar)"
echo "     ✗ WRONG:     #1a1a1a or dark colors (dark sidebar = FAILED)"
echo ""
echo "  2. Header Background"
echo "     ✓ CORRECT:   #FFFFFF (White)"
echo "     ✗ WRONG:     #1a1a1a or dark colors (dark header = FAILED)"
echo ""
echo "  3. Page/Dashboard Background"
echo "     ✓ CORRECT:   #F4F6F8 (Light gray)"
echo "     ✗ WRONG:     #1a1a1a or dark colors (dark page = FAILED)"
echo ""
echo "  4. Primary Text"
echo "     ✓ CORRECT:   #2C3E50 (Dark blue-gray)"
echo "     ✗ WRONG:     #ffffff or light colors (light text = FAILED)"
echo ""
echo "  5. Job Card Headers"
echo "     ✓ CORRECT:   #73A657 (Turf Green)"
echo "     ✗ WRONG:     Any dark color (FAILED)"
echo ""
echo "  6. Button Colors"
echo "     Help:    #EAB35E (Orange)"
echo "     Grey:    #95A5A6 (Gray)"
echo "     Green:   #73A657 (Turf Green)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "STEP 3: Layout Dimension Verification"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Use DevTools Inspector to measure (select element → see width/height):"
echo ""
echo "  ✓ Sidebar:     60px width"
echo "  ✓ Header:      60px height"
echo "  ✓ Right Panel: 300px width"
echo "  ✓ Job Cards:   280px minimum (responsive grid)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "STEP 4: Overall Visual Comparison"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Compare the two windows VISUALLY:"
echo ""
echo "  Does the React app look like the mockup?"
echo "  - Same colors? (green sidebar, light background, white header)"
echo "  - Same layout? (sidebar left, header top, cards in grid)"
echo "  - Same spacing? (proper padding and gaps)"
echo "  - Same typography? (proper font sizes and weights)"
echo ""
echo "If the answer to ANY of these is NO → STOP and fix it"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "STEP 5: Build Verification"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
cd /home/cpbjr/WhitePineTech/Projects/turfsheet-app

if npm run build 2>&1 | tee /tmp/build-output.log; then
  echo ""
  echo "✓ Build successful"
else
  echo ""
  echo "✗ Build FAILED - Fix errors above before continuing"
  echo ""
  exit 1
fi

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ✅ VALIDATION CHECKLIST COMPLETE"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Before committing, confirm:"
echo "  ✓ Colors match mockup exactly (checked with DevTools)"
echo "  ✓ Layout dimensions are correct (60px sidebar, 60px header, etc.)"
echo "  ✓ Visual appearance matches mockup (side-by-side comparison done)"
echo "  ✓ Build succeeds with no errors"
echo ""
echo "Only if ALL of the above are true, you may commit."
echo ""
